In [15]:
import random 
import sys



MINIMUM = 1

MAXIMUM = 9 
NUMBER = random.randint(MINIMUM,MAXIMUM)
GUESS = None
ANOTHER = None

TRY = 0

RUNNING = True

print("Alright...")


while RUNNING:
    
    GUESS = input("What is your lucky number? ")
    
    if int(GUESS) < NUMBER:
        print("Wrong, too low.")

    elif int(GUESS) > NUMBER:
        print("Wrong, too high.")
    elif GUESS.lower() == "exit":
        print("Better luck next time.")
        GUESS = int(GUESS)
        
    elif int(GUESS) == NUMBER:
        print("Yes, that's the one, %s." %str(TRY))
        
        if TRY < 2:
            print("Impressive, only %s tries." %str(TRY))
            
        elif TRY > 2 and TRY < 10:
            print("Pretty good, %s tries." %str(TRY))
            
        else:
            print("Bad, %s tries." %str(TRY))
            
    RUNNING = False
TRY += 1
print('')
    

Alright...
What is your lucky number? 6
Wrong, too high.



In [2]:
import numpy as np
import numpy.random as rdm
from math import sqrt

def py_std(x):
    mean_val = sum(x) / len(x)
    return sqrt(sum((val-mean_val)**2 for val in x)/ len(x))

large_array = rdm.normal(size= (1000000,))

print(py_std(large_array))
print(np.std(large_array))

%timeit py_std(large_array)
%timeit np.std(large_array)

0.9992766881085402
0.9992766881085516
729 ms ± 65.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
7.93 ms ± 414 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Filmato come tensore

In [1]:
import numpy as np 
import numpy.random as rdm

n_frames = 50
n_pixel_x = 5
n_pixel_y = 5

movie = rdm.randint(0, 250 , (n_frames, n_pixel_y, n_pixel_x))

print(movie)

[[[ 27 223 121  68 119]
  [ 68 231 240 220 115]
  [  2 181 248 194 158]
  [248 217  55 245 159]
  [195  93 104   5 201]]

 [[104 147  29  24 113]
  [146   9 206 248 132]
  [158 154 108 226  76]
  [165  56   6 126  98]
  [216  95  50  30 114]]

 [[155 230 127 234 235]
  [  8   3 111 239 131]
  [136  45  15 238 218]
  [224 218 104  13  41]
  [202 191 229 109  21]]

 ...

 [[  5 211  13 103 106]
  [154  24 249 236 154]
  [  5 216  33 216  78]
  [ 26 126  44   9 244]
  [ 10 199  90  86  92]]

 [[ 33 136 230 154   4]
  [ 25  35 247 213 200]
  [ 51 178 107 184 226]
  [182   2  15 243  60]
  [242 126 214  84  67]]

 [[178 222  85 136  18]
  [219 157  23 247 208]
  [235  99  39  35  65]
  [239  70 189  14  61]
  [ 60  95  13 200 193]]]


In [2]:
print(movie.shape)

(50, 5, 5)


In [4]:
pixel_mean_intensity = np.mean(movie, axis = 0)
print(pixel_mean_intensity)
print(pixel_mean_intensity.shape)

[[131.1  124.58 121.22 141.76 116.24]
 [119.46 112.64 126.3  139.62 127.66]
 [121.54 108.86 120.48 147.62 120.4 ]
 [119.86 129.   109.88 135.64 135.2 ]
 [122.56 123.86 113.2   93.34 134.66]]
(5, 5)


In [8]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


# 2

In [14]:
import numpy as np
import numpy.random as rdm 

array_norm = rdm.normal(5,3, 1000000)

#sottraggo 5 e guardo se ha funzionato
print(round(np.mean(array_norm), 4))
array_norm -= 5
print(round(np.mean(array_norm), 4))

#implemento la deviazione std e confronto con np.std
residuals = array_norm - np.mean(array_norm)
squared_residuals = residuals**2
variance = np.sum(squared_residuals)/ array_norm.size
print(np.std(array_norm), np.sqrt(variance))


5.0024
0.0024
2.9996382103325687 2.9996382103325687


In [1]:
import os 
os.getcwd()


'C:\\Users\\vgiov'